name: 'Inkly Build'

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-11
            npmCmd: npm
            buildCmd: electron-packager app Inky --platform=darwin --arch=x64 --icon=resources/Icon.icns --extend-info=resources/info.plist --app-bundle-id=com.inkle.inky --prune --asar.unpackDir="main-process/ink" --ignore="inklecate_win.exe"
            createInstallerCmd: appdmg resources/appdmg.json ReleaseUpload/Inky_mac.dmg

          - os: windows-latest
            npmCmd: call npm
            buildCmd: call electron-packager app Inky --platform=win32  --arch=x64 --icon=resources/Icon1024.png.ico --prune --asar.unpackDir="main-process/ink" --ignore="inklecate_mac" --win32metadata.ProductName="Inky" --win32metadata.CompanyName="inkle Ltd" --win32metadata.FileDescription="Inky" --win32metadata.OriginalFilename="Inky" --win32metadata.InternalName="Inky"
            createInstallerCmd: powershell Compress-Archive Inky-win32-x64 ReleaseUpload\Inky-win32-x64.zip 

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '17'

      - name: Install Dependencies
        run: |
          ${{ matrix.npmCmd }} install -g \
            electron-packager \
            appdmg

          cd app
          ${{ matrix.npmCmd }} install

      - name: Build Icon
        if: matrix.os == 'macos-11'
        run: |
          cd app
          ./resources/makeIcns.command
          
      - name: Build Package
        run: |
          ${{ matrix.buildCmd }}

      - name: Create Installer
        run: |
          mkdir ReleaseUpload
          ${{ matrix.createInstallerCmd }}

      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.os }}
          path: |
            ReleaseUpload/Inky_mac.dmg
            ReleaseUpload/Inky-win32-x64.zip
